"""
Canonical phrases for voice command recognition.
These phrases are used for semantic matching of voice commands.
"""

CANONICAL_PHRASES = {
    "play": [
        # French phrases
        "lancer la vidéo",
        "démarrer la lecture",
        "commencer la lecture",
        "reprendre la lecture",
        "continuer la lecture",
        "mettre en lecture",
        "lancer le film",
        "démarrer le film",
        "lancer le replay",
        "démarrer le replay",
        # English phrases
        "play the video",
        "start playing",
        "resume the video",
        "continue playing",
        "play the movie",
        "start the movie",
        "play the replay",
        "start the replay",
        # Simple words and verb variations
        "play",
        "jouer",
        "joue",
        "joues",
        "start",
        "démarrer",
        "démarre",
        "démarres",
        "lancer",
        "lance",
        "lances",
        "go",
        "aller",
        "va",
        "vas",
    ],
    "pause": [
        # French phrases
        "mettre en pause",
        "arrêter la lecture",
        "stopper la vidéo",
        "stopper la lecture",
        "stop la vidéo",
        "faire une pause",
        "interrompre la lecture",
        "mettre le film en pause",
        "arrêter le film",
        "stopper le film",
        "mettre le replay en pause",
        "arrêter le replay",
        # English phrases
        "pause the video",
        "stop playing",
        "halt the video",
        "pause the movie",
        "stop the movie",
        "pause the replay",
        "stop the replay",
        # Simple words and verb variations
        "pause",
        "pauser",
        "pause",
        "pauses",
        "stop",
        "arrêter",
        "arrête",
        "arrêtes",
        "stopper",
        "stoppe",
        "stoppes",
        "halt",
        "interrompre",
        "interrompt",
        "interromps",
    ],
    "forward": [
        # French phrases
        "avancer",
        "aller en avant",
        "passer en avant",
        "avancer la vidéo",
        "faire avancer",
        "passer à la suite",
        "avancer le film",
        "passer le film en avant",
        "avancer le replay",
        "passer le replay en avant",
        # English phrases
        "skip forward",
        "move forward",
        "go forward",
        "advance the video",
        "skip ahead",
        "move ahead",
        "go ahead",
        "advance the movie",
        "skip the movie forward",
        "advance the replay",
        # Simple words and verb variations
        "forward",
        "avancer",
        "avance",
        "avances",
        "skip",
        "next",
        "suivant",
        "ahead",
        "avant",
    ],
    "backward": [
        # French phrases
        "reculer",
        "aller en arrière",
        "passer en arrière",
        "reculer la vidéo",
        "faire reculer",
        "revenir en arrière",
        "reculer le film",
        "passer le film en arrière",
        "reculer le replay",
        "passer le replay en arrière",
        # English phrases
        "go back",
        "move backward",
        "rewind the video",
        "skip backward",
        "go backward",
        "move back",
        "rewind the movie",
        "skip the movie backward",
        "rewind the replay",
        # Simple words and verb variations
        "back",
        "reculer",
        "recule",
        "recules",
        "backward",
        "rewind",
        "retour",
        "arrière",
        "previous",
        "précédent",
    ],
    "tag": [
        # French phrases
        "ajouter un tag",
        "créer un tag",
        "marquer ce point",
        "ajouter un marqueur",
        "poser un tag",
        "mettre un tag",
        "ajouter un repère",
        "créer un repère",
        "marquer un point",
        "ajouter un point de repère",
        # English phrases
        "add a tag",
        "create a tag",
        "mark this point",
        "add a marker",
        "place a tag",
        "put a tag",
        "add a bookmark",
        "create a bookmark",
        "mark a point",
        "add a reference point",
        # Simple words and verb variations
        "tag",
        "tagger",
        "tag",
        "tagges",
        "marker",
        "marqueur",
        "bookmark",
        "repère",
        "mark",
        "marquer",
        "marque",
        "marques",
    ],
    "record": [
        # French phrases
        "démarrer l'enregistrement",
        "commencer l'enregistrement",
        "lancer l'enregistrement",
        "démarrer la capture",
        "commencer la capture",
        "lancer la capture",
        "démarrer l'enregistrement vidéo",
        "commencer l'enregistrement vidéo",
        "lancer l'enregistrement vidéo",
        "démarrer la capture vidéo",
        # English phrases
        "start recording",
        "begin recording",
        "start capture",
        "begin capture",
        "start video recording",
        "begin video recording",
        "start video capture",
        "begin video capture",
        "start filming",
        "begin filming",
        # Simple words and verb variations
        "record",
        "enregistrer",
        "enregistre",
        "enregistres",
        "capture",
        "capturer",
        "capture",
        "captures",
        "film",
        "filmer",
        "filme",
        "filmes",
    ],
    "stop_record": [
        # French phrases
        "arrêter l'enregistrement",
        "stopper l'enregistrement",
        "terminer l'enregistrement",
        "arrêter la capture",
        "stopper la capture",
        "terminer la capture",
        "arrêter l'enregistrement vidéo",
        "stopper l'enregistrement vidéo",
        "terminer l'enregistrement vidéo",
        "arrêter la capture vidéo",
        # English phrases
        "stop recording",
        "end recording",
        "stop capture",
        "end capture",
        "stop video recording",
        "end video recording",
        "stop video capture",
        "end video capture",
        "stop filming",
        "end filming",
        # Simple words and verb variations
        "stop",
        "arrêter",
        "arrête",
        "arrêtes",
        "end",
        "terminer",
        "termine",
        "termines",
        "finish",
        "finir",
        "fini",
        "finis",
    ],
    "live": [
        # French phrases
        "passer en mode direct",
        "aller en mode direct",
        "activer le mode direct",
        "afficher le mode direct",
        "basculer en mode direct",
        "changer en mode direct",
        "passer en direct",
        "aller en direct",
        "activer le direct",
        "afficher le direct",
        # English phrases
        "switch to live mode",
        "go to live mode",
        "enter live mode",
        "show live view",
        "activate live mode",
        "display live mode",
        "switch to live",
        "go to live",
        "enter live",
        "show live",
        # Simple words and verb variations
        "live",
        "direct",
        "stream",
        "streaming",
    ],
    "review": [
        # French phrases
        "passer en mode révision",
        "aller en mode révision",
        "activer le mode révision",
        "afficher le mode révision",
        "basculer en mode révision",
        "changer en mode révision",
        "passer en révision",
        "aller en révision",
        "activer la révision",
        "afficher la révision",
        # English phrases
        "switch to review mode",
        "go to review mode",
        "enter review mode",
        "show review view",
        "activate review mode",
        "display review mode",
        "switch to review",
        "go to review",
        "enter review",
        "show review",
        # Simple words and verb variations
        "review",
        "révision",
        "replay",
        "playback",
    ],
    "open": [
        # French phrases
        "ouvrir un fichier",
        "ouvrir une vidéo",
        "charger un fichier",
        "charger une vidéo",
        "importer un fichier",
        "importer une vidéo",
        "ouvrir un film",
        "charger un film",
        "importer un film",
        "ouvrir un replay",
        # English phrases
        "open a file",
        "open video",
        "load a file",
        "load video",
        "import a file",
        "import video",
        "open a movie",
        "load a movie",
        "import a movie",
        "open a replay",
        # Simple words and verb variations
        "open",
        "ouvrir",
        "ouvre",
        "ouvres",
        "load",
        "charger",
        "charge",
        "charges",
        "import",
        "importer",
        "importe",
        "importes",
    ],
}

# Mapping from semantic intents to actual commands
INTENT_TO_COMMAND = {
    "play": "play",
    "pause": "pause",
    "forward": "avancer",
    "backward": "reculer",
    "tag": "ajouter un tag",
    "record": "démarrer enregistrement",
    "stop_record": "arrêter enregistrement",
    "live": "mode direct",
    "review": "mode révision",
    "open": "ouvrir",
}
