"""
Canonical phrases for voice command recognition.
These phrases are used for semantic matching of voice commands.
"""

# Trigger words that must be present in a command
TRIGGER_PHRASES = ["logiciel", "application", "caméra"]

# Important words that give bonus to command matching
IMPORTANT_WORDS = {
    "ouvrir",
    "play",
    "pause",
    "avancer",
    "reculer",
    "tag",
    "enregistrer",
    "direct",
    "révision",
}


CANONICAL_PHRASES = {
    "play": [
        # French phrases
        "démarrer la lecture",
        "commencer la lecture",
        "reprendre la lecture",
        "continuer la lecture",
        "mettre en lecture",
        "lancer le film",
        "démarrer le film",
        "lancer la lecture",
        "démarrer la lecture",
        "reprendre la lecture",
        "continuer la lecture",
        "mettre en lecture",
        "démarre la lecture",
        "démarre le film",
        "démarre la lecture",
        "démarre le film",
        "démarre la lecture",
        "démarre le film",
        # Simple words and verb variations
        "lecture",
        "lectures",
        "lire",
        "jouer",
        "joue",
        "joues",
        "start",
        "démarrer",
        "démarre",
        "démarres",
        "lancer",
        "lance",
        "lances",
    ],
    "pause": [
        # French phrases
        "mettre en pause",
        "arrêter la lecture",
        "stopper",
        "stopper la lecture",
        "faire une pause",
        "interrompre la lecture",
        "mettre le film en pause",
        "arrêter le film",
        "stopper le film",
        # English phrases
        "pause the video",
        "halt the video",
        "pause the movie",
        "stop the movie",
        # Simple words and verb variations
        "pause",
        "pauser",
        "pause",
        "pauses",
        "stop",
        "arrêter",
        "arrête",
        "arrêtes",
        "stopper",
        "stoppe",
        "stoppes",
        "halt",
        "interrompre",
        "interrompt",
        "interromps",
    ],
    "forward": [
        # French phrases
        "avancer",
        "passer en avant",
        "faire avancer",
        "passer à la suite",
        "avancer le film",
        "passer le film en avant",
        # English phrases
        "skip forward",
        "move forward",
        "go forward",
        "advance the video",
        "skip ahead",
        "move ahead",
        "go ahead",
        "advance the movie",
        "skip the movie forward",
        # Simple words and verb variations
        "forward",
        "avancer",
        "avance",
        "avances",
        "skip",
        "next",
        "suivant",
        "ahead",
        "avant",
    ],
    "backward": [
        # French phrases
        "reculer",
        "passer en arrière",
        "faire reculer",
        "revenir en arrière",
        "reculer le film",
        "passer le film en arrière",
        # English phrases
        "go back",
        "move backward",
        "rewind the video",
        "skip backward",
        "go backward",
        "move back",
        "rewind the movie",
        "skip the movie backward",
        # Simple words and verb variations
        "back",
        "reculer",
        "recul",
        "recule",
        "recules",
        "backward",
        "rewind",
        "retour",
        "arrière",
        "previous",
        "précédent",
    ],
    "tag": [
        # French phrases
        "ajouter un tag",
        "créer un tag",
        "marquer ce point",
        "ajouter un marqueur",
        "poser un tag",
        "mettre un tag",
        "ajouter un repère",
        "créer un repère",
        "marquer un point",
        "ajouter un point de repère",
        "ajoute un tag",
        "ajoute un repère",
        "ajoute un marqueur",
        "ajoute un marqueur",
        "ajoute un marqueur",
        "ajoute un marqueur",
        "ajoute un marqueur",
        # English phrases
        "add a tag",
        "create a tag",
        "mark this point",
        "add a marker",
        "place a tag",
        "put a tag",
        "add a bookmark",
        "create a bookmark",
        "mark a point",
        "add a reference point",
        # Simple words and verb variations
        "tags",
        "tag",
        "tage",
        "tagger",
        "tag",
        "tagges",
        "marker",
        "marqueur",
        "bookmark",
        "repère",
        "mark",
        "marquer",
        "marque",
        "marques",
    ],
    "record": [
        # French phrases
        "démarrer l'enregistrement",
        "commencer l'enregistrement",
        "lancer l'enregistrement",
        "démarrer la capture",
        "commencer la capture",
        "lancer la capture",
        # English phrases
        "start recording",
        "begin recording",
        "start capture",
        "begin capture",
        "start video recording",
        "begin video recording",
        "start video capture",
        "begin video capture",
        "start filming",
        "begin filming",
        # Simple words and verb variations
        "record",
        "enregistrer",
        "enregistre",
        "enregistres",
        "enregistrement",
        "enregistrements",
        "capture",
        "capturer",
        "capture",
        "captures",
        "film",
        "filmer",
        "filme",
        "filmes",
    ],
    "stop_record": [
        # French phrases
        "arrêter l'enregistrement",
        "arrête l'enregistrement",
        "stop l'enregistrement",
        "stop la capture",
        "termine l'enregistrement",
        "stopper l'enregistrement",
        "terminer l'enregistrement",
        "arrêter la capture",
        "stopper la capture",
        "terminer la capture",
        "arrêter l'enregistrement vidéo",
        "stopper l'enregistrement vidéo",
        "terminer l'enregistrement vidéo",
        "arrêter la capture vidéo",
        # English phrases
        "stop recording",
        "end recording",
        "stop capture",
        "end capture",
        "stop video recording",
        "end video recording",
        "stop video capture",
        "end video capture",
        "stop filming",
        "end filming",
        # Simple words and verb variations
        "stop",
        "arrêter",
        "arrête",
        "arrêtes",
        "end",
        "terminer",
        "termine",
        "termines",
        "finish",
        "finir",
        "fini",
        "finis",
    ],
    "live": [
        # French phrases
        "passer en mode direct",
        "activer le mode direct",
        "afficher le mode direct",
        "basculer en mode direct",
        "changer en mode direct",
        "passer en direct",
        "activer le direct",
        "afficher le direct",
        # English phrases
        "switch to live mode",
        "go to live mode",
        "enter live mode",
        "show live view",
        "activate live mode",
        "display live mode",
        "switch to live",
        "go to live",
        "enter live",
        "show live",
        # Simple words and verb variations
        "live",
        "direct",
        "directe",
        "directes",
        "stream",
        "streaming",
    ],
    "review": [
        # French phrases
        "passer en mode révision",
        "activer le mode révision",
        "afficher le mode révision",
        "basculer en mode révision",
        "changer en mode révision",
        "passer en révision",
        "activer la révision",
        "afficher la révision",
        "passer en mode relecture",
        "activer le mode relecture",
        "afficher le mode relecture",
        "basculer en mode relecture",
        "changer en mode relecture",
        "passer en relecture",
        "activer la relecture",
        "afficher la relecture",
        # English phrases
        "switch to review mode",
        "go to review mode",
        "enter review mode",
        "show review view",
        "activate review mode",
        "switch to review",
        "go to review",
        "enter review",
        "show review",
        # Simple words and verb variations
        "review",
        "révision",
        "révisione",
        "réunion",
        "playback",
        "visionnage",
        "visionner",
        "revisionner",
        "revision",
        "revisionnage",
        "relecture",
        "relire",
        "relis",
        "relisant",
        "revoir",
        "revois",
        "revoyant",
    ],
    "open": [
        # French phrases
        "ouvrir un fichier",
        "ouvrir une vidéo",
        "ouvre la vidéo",
        "ouvre une vidéo",
        "charger un fichier",
        "charger une vidéo",
        "importer un fichier",
        "importer une vidéo",
        "ouvrir un film",
        "charger un film",
        "importer un film",
        "ouvrir un replay",
        # English phrases
        "open a file",
        "open video",
        "load a file",
        "load video",
        "import a file",
        "import video",
        "open a movie",
        "load a movie",
        "import a movie",
        "open a replay",
        # Simple words and verb variations
        "open",
        "ouvrir",
        "ouvre",
        "ouvres",
        "load",
        "charger",
        "charge",
        "charges",
        "import",
        "importer",
        "importe",
        "importes",
    ],
    "open_last_video": [
        "recharger la dernière vidéo",
        "reprendre la dernière vidéo",
        "retourner à la dernière vidéo",
        "revoir la dernière vidéo",
        "recharger le dernier enregistrement",
        "reprendre le dernier enregistrement",
        "retourner au dernier enregistrement",
        "revoir le dernier enregistrement",
        "dernier enregistrement",
        "dernière capture",
        "dernier film",
        "dernière séquence",
        "lire la dernière vidéo",
        "lire le dernier enregistrement",
    ],
    "goto_tag": [
        "aller au tag",
        "aller à tag",
        "aller au marqueur",
        "aller à marqueur",
        "aller au repère",
        "aller à repère",
        "aller au point",
        "aller à point",
        "naviguer au tag",
        "naviguer à tag",
        "naviguer au marqueur",
        "naviguer à marqueur",
        "naviguer au repère",
        "naviguer à repère",
        "naviguer au point",
        "naviguer à point",
    ],
    "zoom": [
        "zoomer",
        "zoomer en avant",
        "zoomer en arrière",
        "zoomer en avant",
        "zoomer en arrière",
        "zoom",
        "agrandir",
        "agrandis",
    ],
    "zoom_in": [
        "agrandir",
        "agrandis",
        "agrandi",
        "agrandie" "agrandir la vidéo",
        "agrandis la vidéo",
        "agrandi la vidéo",
    ],
    "zoom_out": [
        "réduire",
        "rédui la vidéo",
        "réduit la vidéo",
        "réduis la vidéo",
    ],
}

# Mapping from semantic intents to actual commands
INTENT_TO_COMMAND = {
    "play": "play",
    "pause": "pause",
    "forward": "avancer",
    "backward": "reculer",
    "tag": "ajouter un tag",
    "record": "démarrer enregistrement",
    "stop_record": "arrêter enregistrement",
    "live": "mode direct",
    "review": "mode révision",
    "open": "ouvrir",
    "goto_tag": "aller au tag",
}
