name: Build ICNS

on:
  push:
    paths:
      - 'src/resources/images/Logo-CookiNUM-filled-1024.png'
    branches: [macos_installer]
  workflow_dispatch:

jobs:
  build-icns:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create iconset folder
      run: |
        mkdir -p icon.iconset
        for size in 16 32 64 128 256 512 1024; do
          s1=$size
          s2=$(($size * 2))
          sfx1="${s1}x${s1}"
          sfx2="${s1}x${s1}@2x"
          sfile1="icon.iconset/icon_${sfx1}.png"
          sfile2="icon.iconset/icon_${sfx2}.png"
          sips -z $s1 $s1 src/resources/images/Logo-CookiNUM-filled-1024.png --out $sfile1
          sips -z $s2 $s2 src/resources/images/Logo-CookiNUM-filled-1024.png --out $sfile2
        done

    - name: Verify iconset structure
      run: |
        ls -la icon.iconset/
        if [ ! -d "icon.iconset" ]; then
          echo "Error: icon.iconset directory not created"
          exit 1
        fi

    - name: Convert iconset to icns
      run: |
        mkdir -p src/resources/images
        iconutil -c icns icon.iconset -o src/resources/images/app.icns
        if [ ! -f "src/resources/images/app.icns" ]; then
          echo "Error: ICNS file not generated"
          exit 1
        fi

    - name: Upload ICNS as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app.icns
        path: src/resources/images/app.icns
