name: Test macos app in dev mode with logs

on:
  push:
    branches: [macos_installer]

jobs:
  test-dev:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install VLC
        run: |
          brew install vlc

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run app in dev mode (non blocking)
        run: |
          LOG_DIR="logs"
          mkdir -p "$LOG_DIR"
          echo "=== Lancement de l'app ==="
          # Lance l'app en arrière-plan
          python -m src.core.main &
          APP_PID=$!
          sleep 15
          if ps -p $APP_PID > /dev/null; then
            echo "App is running correctly after 15 seconds ✅"
            kill $APP_PID
          else
            echo "App terminated before 15 seconds ❌"
            exit 1
          fi

      - name: Print log preview
        run: |
          LOG_FILE="logs/cookinum.log"
          echo "===== Log preview ====="
          if [ -f "$LOG_FILE" ]; then
            tail -n 30 "$LOG_FILE"
          else
            echo "No log file found"
          fi

      - name: Upload app logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: DevApp-logs-macOS
          path: logs/

      - name: Build installer
        run: |
          pyinstaller CookiNUMnetwork.spec
          # Vérifier que l'app a été créée
          if [ -d "dist/CookiNUMnetwork.app" ]; then
            echo "✅ App built successfully"
          else
            echo "❌ App build failed"
            exit 1
          fi

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: CookiNUMnetwork-macOS
          path: dist/CookiNUMnetwork.app
