name: Test windows app in dev mode with logs

on:
  push:
    branches: [windows_installer]

jobs:
  test-dev:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run app in dev mode (non blocking)
        run: |
          mkdir logs
          echo "=== Lancement de l'app ==="
          start /B python -m src.core.main
          timeout /T 15
          tasklist | findstr python || (
            echo App terminated before 15 seconds ❌
            exit 1
          )
          echo App is running correctly after 15 seconds ✅
          taskkill /IM python.exe /F

      - name: Print log preview
        run: |
          echo ===== Log preview =====
          if exist logs\cookinum.log (
            type logs\cookinum.log
          ) else (
            echo No log file found
          )

      - name: Upload app logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: DevApp-logs-Windows
          path: logs\

      - name: Build installer
        run: |
          pyinstaller CookiNUMnetwork.spec
          if exist dist\CookiNUMnetwork\CookiNUMnetwork.exe (
            echo ✅ .exe built successfully
          ) else (
            echo ❌ Build failed
            exit 1
          )

      - name: Test built installer
        run: |
          echo === Testing built installer ===
          start /B dist\CookiNUMnetwork\CookiNUMnetwork.exe
          timeout /T 15
          tasklist | findstr CookiNUMnetwork || (
            echo ❌ Built app terminated before 15 seconds
            if exist "%APPDATA%\CookiNUM\logs\cookinum.log" (
              echo ===== App logs =====
              type "%APPDATA%\CookiNUM\logs\cookinum.log"
            ) else (
              echo No log file found at %APPDATA%\CookiNUM\logs\cookinum.log
            )
            exit 1
          )
          echo ✅ Built app is running correctly after 15 seconds
          taskkill /IM CookiNUMnetwork.exe /F

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: CookiNUMnetwork-Windows
          path: dist\CookiNUMnetwork\
