name: Test app Windows in dev mode with logs

on:
  push:
    branches: [windows_installer]

jobs:
  test-dev-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check resource presence
        run: dir src/resources/icons
        shell: powershell

