name: Test Windows app in dev mode with logs

on:
  push:
    branches: [windows_installer]

jobs:
  test-dev:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run app in dev mode (non blocking)
        shell: cmd
        run: |
          mkdir logs
          echo === Lancement de l'app ===
          start /B python -m src.core.main
          timeout /T 15
          tasklist | findstr python >nul
          if errorlevel 1 (
            echo App terminated before 15 seconds ❌
            exit 1
          ) else (
            echo App is running correctly after 15 seconds ✅
            taskkill /IM python.exe /F
          )

      - name: Print log preview
        run: |
          $logPath = "logs/cookinum.log"
          if (Test-Path $logPath) {
            Write-Host "===== Log preview ====="
            Get-Content $logPath -Tail 30
          } else {
            Write-Host "No log file found"
          }
        shell: pwsh

      - name: Upload app logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: DevApp-logs-windows
          path: logs/

      - name: Build installer (PyInstaller)
        run: pyinstaller CookiNUMnetwork.spec

      - name: Test built executable
        shell: cmd
        run: |
          echo === Testing built EXE ===
          if not exist dist\CookiNUMnetwork\CookiNUMnetwork.exe (
            echo ❌ EXE not found in dist\
            exit 1
          )
          start /B dist\CookiNUMnetwork\CookiNUMnetwork.exe
          timeout /T 15
          tasklist | findstr CookiNUMnetwork.exe >nul
          if errorlevel 1 (
            echo ❌ App terminated before 15 seconds
            exit 1
          ) else (
            echo ✅ EXE is running correctly after 15 seconds
            taskkill /IM CookiNUMnetwork.exe /F
          )

      - name: Upload built EXE
        uses: actions/upload-artifact@v4
        with:
          name: CookiNUMnetwork-windows
          path: dist/CookiNUMnetwork/CookiNUMnetwork.exe
